spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booksdb
    username: PostgreSQL 17
    password:
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelogs/db.changelog-master.yaml