name: Kotlin CI with JaCoCo and PIT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build and run unit tests (with JaCoCo)
        run: ./gradlew clean build

      - name: Run PIT mutation tests
        run: ./gradlew pitest

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Upload PIT mutation report
        uses: actions/upload-artifact@v4
        with:
          name: pitest-report
          path: build/reports/pitest
